server:
  port: 8761
  servlet:
    context-path: /discovery

spring:
  application:
    name: discoveryservice
  profiles:
    active: local

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/discovery/eureka/
