server:
  port: 8761
  servlet:
    context-path: /discovery

spring:
  application:
    name: discoveryservice
  #cloud:
  #  config:
  #    uri: http://127.0.0.1:8888
  #    name: discovery-config

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/server/eureka/
