apiVersion: apps/v1
kind: Deployment
metadata:
  name: discoveryserver
  namespace: sj-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discoveryserver
  template:
    metadata:
      labels:
        app: discoveryserver
    spec:
      containers:
        - name: discoveryserver
          image: sj-lab-registry.kr.ncr.ntruss.com/sj-lab-discoveryserver:latest  # ← 실제 이미지명으로 수정
          ports:
            - containerPort: 8761
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: discoveryserver-config
